#applicants deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants-deployment
  namespace: appscore
  labels:
    app: applicants
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicants-pod
  template:
    metadata:
      labels:
        app: applicants-pod
    spec:
      containers:

        - name: applicants-container
          image: azed01/k8s:applicants
          ports:
            - containerPort: 80
              name: applicants-port
          env:
          - name: ConnectionString
            value: "Server=database-service;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;"
          - name: HostRabbitmq
            value: "rabbitmq-service"
          resources:
            requests:
              cpu: "0.5"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1500Mi"
      restartPolicy: Always
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                 matchExpressions:
                   - key: app
                     operator: In
                     values:
                       - database-service
              topologyKey: "kubernetes.io/hostname"
---
#applicants service
apiVersion: v1
kind: Service
metadata:
  name: applicants-service
  namespace: appscore
spec:
  selector:
    app: applicants-pod
  ports:
    - port: 80
      name: applicants-port
      targetPort: 80
      protocol: TCP
  type: ClusterIP